### ISSUE TITLE
Missing square brackets in join()

### ISSUE THREAD

**Issue by belphegor-belbel** [openSUSE/rpmlint-checks#46]
https://github.com/openSUSE/rpmlint-checks/blob/2d11e76027fc32be4005f955a71fab84c3a5407d/CheckPolkitPrivs.py#L173

Should it be "path = '.'.join([f, profile])" (add square brackets)?
It seemed to cause RPMLINT error in Open Build Service as follows:

https://build.opensuse.org/package/live_build_log/home:belphegor_belbel:KDE3/hal/openSUSE_Tumbleweed/x86_64
> [  109s] RPMLINT report:
> [  109s] ===============
> [  111s] 0 packages and 0 specfiles checked; 0 errors, 13 warnings.
> [  111s] Traceback (most recent call last):
> [  111s]   File "rpmlint.py", line 378, in <module>
> [  111s]   File "rpmlint.py", line 166, in main
> [  111s]   File "rpmlint.py", line 224, in runChecks
> [  111s]   File "CheckPolkitPrivs.py", line 335, in check
> [  111s]   File "CheckPolkitPrivs.py", line 173, in check_perm_files
> [  111s] TypeError: join() takes exactly one argument (2 given)

**Comment by mgerstner** [comment]
You're right this is a bug I introduced when refactoring the Polkit check. Sorry but I didn't notice you issue before and nobody informed be. I will submit a fix for Tumbleweed.
