### ISSUE TITLE
Archive the repository

### ISSUE THREAD

**Issue by marxin** [openSUSE/rpmlint-checks#68]
After the 2.1 release of [rpmlint](https://github.com/rpm-software-management/rpmlint/releases/tag/2.1.0) and after the acceptance of the package to openSUSE:Factory, this repository should be archived.

**Comment by marxin** [comment]
Can you please do it @jsegitz or @mgerstner ?

**Comment by jsegitz** [comment]
As long as this is still used in older SLES versions I would rather like to keep it as is, but add a note that this isn't relevant for openSUSE Tumbleweed/Factory anymore. @dirkmueller What do you think? It's probably mostly your decision

**Comment by marxin** [comment]
@dirkmueller: May I please ping this?

**Comment by dirkmueller** [comment]
@marxin we're still using this repo for rpmlint 1.x in openSUSE Leap/SLE. I have made the README more clear that future  checks should be sent upstream. is that sufficient?

**Comment by marxin** [comment]
> is that sufficient?

Sure!
